[2025-07-21T14:19:52.443+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:19:52.445+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:19:52.446+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:19:52.446+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:19:52.456+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:19:52.456+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/put_data_to_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/put_data_to_db.py", line 18
    res = response.json()
    ^
IndentationError: expected an indented block
[2025-07-21T14:19:52.457+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:19:52.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.039 seconds
[2025-07-21T14:20:21.341+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:20:21.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:20:21.343+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:20:21.343+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:20:21.359+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:20:21.357+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/put_data_to_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/put_data_to_db.py", line 18
    res = response.json()
    ^
IndentationError: expected an indented block
[2025-07-21T14:20:21.359+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:20:21.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.042 seconds
[2025-07-21T14:20:51.580+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:20:51.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:20:51.582+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:20:51.582+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:20:51.596+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:20:51.595+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/put_data_to_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/put_data_to_db.py", line 18
    res = response.json()
    ^
IndentationError: expected an indented block
[2025-07-21T14:20:51.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:20:51.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.039 seconds
[2025-07-21T14:20:54.644+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:20:54.645+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:20:54.647+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:20:54.647+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:20:54.664+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:20:54.663+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/put_data_to_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/put_data_to_db.py", line 18
    res = response.json()
    ^
IndentationError: expected an indented block
[2025-07-21T14:20:54.665+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:20:54.688+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.047 seconds
[2025-07-21T14:20:58.714+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:20:58.715+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:20:58.716+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:20:58.716+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:20:58.726+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:20:58.725+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/put_data_to_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/put_data_to_db.py", line 18
    res = response.json()
    ^
IndentationError: expected an indented block
[2025-07-21T14:20:58.727+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:20:58.746+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.035 seconds
[2025-07-21T14:21:00.752+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:21:00.753+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:21:00.754+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:21:00.754+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:21:00.763+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:21:00.762+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/put_data_to_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/put_data_to_db.py", line 18
    res = response.json()
    ^
IndentationError: expected an indented block
[2025-07-21T14:21:00.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:21:00.781+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.032 seconds
[2025-07-21T14:21:31.005+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:21:31.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:21:31.007+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:21:31.006+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:21:31.014+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:21:31.013+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/put_data_to_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/put_data_to_db.py", line 18
    res = response.json()
    ^
IndentationError: expected an indented block
[2025-07-21T14:21:31.015+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:21:31.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.029 seconds
[2025-07-21T14:21:37.075+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:21:37.076+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:21:37.076+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:21:37.076+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:21:37.110+0000] {processor.py:840} INFO - DAG(s) 'hello_two_tasks' retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:21:37.356+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:21:37.356+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:hello_two_tasks
[2025-07-21T14:21:37.371+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:21:37.371+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:hello_two_tasks
[2025-07-21T14:21:37.378+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:21:37.377+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:hello_two_tasks
[2025-07-21T14:21:37.379+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:21:37.379+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-07-21T14:21:37.389+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:21:37.389+0000] {dag.py:3058} INFO - Creating ORM DAG for hello_two_tasks
[2025-07-21T14:21:37.400+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:21:37.400+0000] {dag.py:3823} INFO - Setting next_dagrun for hello_two_tasks to 2025-07-20 00:00:00+00:00, run_after=2025-07-21 00:00:00+00:00
[2025-07-21T14:21:37.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.347 seconds
[2025-07-21T14:22:01.638+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:22:01.639+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:22:01.640+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:22:01.639+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:22:01.665+0000] {processor.py:840} INFO - DAG(s) 'put_data' retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:22:01.761+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:22:01.761+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:put_data
[2025-07-21T14:22:01.772+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:22:01.772+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:put_data
[2025-07-21T14:22:01.781+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:22:01.780+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:put_data
[2025-07-21T14:22:01.782+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:22:01.782+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-07-21T14:22:01.792+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:22:01.792+0000] {dag.py:3058} INFO - Creating ORM DAG for put_data
[2025-07-21T14:22:01.802+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:22:01.801+0000] {dag.py:3823} INFO - Setting next_dagrun for put_data to 2025-07-20 00:00:00+00:00, run_after=2025-07-21 00:00:00+00:00
[2025-07-21T14:22:01.828+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.193 seconds
[2025-07-21T14:22:04.691+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:22:04.693+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:22:04.696+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:22:04.695+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:22:04.739+0000] {processor.py:840} INFO - DAG(s) 'put_data_to_db' retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:22:04.869+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:22:04.868+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:put_data_to_db
[2025-07-21T14:22:04.880+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:22:04.880+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:put_data_to_db
[2025-07-21T14:22:04.887+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:22:04.887+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:put_data_to_db
[2025-07-21T14:22:04.888+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:22:04.888+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-07-21T14:22:04.898+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:22:04.897+0000] {dag.py:3058} INFO - Creating ORM DAG for put_data_to_db
[2025-07-21T14:22:04.910+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:22:04.909+0000] {dag.py:3823} INFO - Setting next_dagrun for put_data_to_db to 2025-07-20 00:00:00+00:00, run_after=2025-07-21 00:00:00+00:00
[2025-07-21T14:22:04.932+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.245 seconds
[2025-07-21T14:22:35.078+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:22:35.079+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:22:35.080+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:22:35.080+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:22:35.098+0000] {processor.py:840} INFO - DAG(s) 'put_data_to_db' retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:22:35.120+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:22:35.120+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-07-21T14:22:35.139+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:22:35.139+0000] {dag.py:3823} INFO - Setting next_dagrun for put_data_to_db to 2025-07-20 00:00:00+00:00, run_after=2025-07-21 00:00:00+00:00
[2025-07-21T14:22:35.160+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.085 seconds
[2025-07-21T14:23:05.301+0000] {processor.py:161} INFO - Started process (PID=224) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:23:05.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:23:05.303+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:23:05.302+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:23:05.319+0000] {processor.py:840} INFO - DAG(s) 'put_data_to_db' retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:23:05.340+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:23:05.340+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-07-21T14:23:05.361+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:23:05.361+0000] {dag.py:3823} INFO - Setting next_dagrun for put_data_to_db to 2025-07-21 00:00:00+00:00, run_after=2025-07-22 00:00:00+00:00
[2025-07-21T14:23:05.384+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.086 seconds
[2025-07-21T14:23:35.554+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:23:35.556+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:23:35.557+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:23:35.556+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:23:35.574+0000] {processor.py:840} INFO - DAG(s) 'put_data_to_db' retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:23:35.598+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:23:35.598+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-07-21T14:23:35.618+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:23:35.618+0000] {dag.py:3823} INFO - Setting next_dagrun for put_data_to_db to 2025-07-21 00:00:00+00:00, run_after=2025-07-22 00:00:00+00:00
[2025-07-21T14:23:35.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.088 seconds
[2025-07-21T14:23:43.758+0000] {processor.py:161} INFO - Started process (PID=234) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:23:43.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:23:43.760+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:23:43.760+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:23:43.786+0000] {processor.py:840} INFO - DAG(s) 'put_data_to_db' retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:23:43.811+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:23:43.811+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-07-21T14:23:43.833+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:23:43.833+0000] {dag.py:3823} INFO - Setting next_dagrun for put_data_to_db to 2025-07-21 00:00:00+00:00, run_after=2025-07-22 00:00:00+00:00
[2025-07-21T14:23:43.864+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.109 seconds
[2025-07-21T14:23:51.839+0000] {processor.py:161} INFO - Started process (PID=239) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:23:51.840+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:23:51.842+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:23:51.841+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:23:51.885+0000] {processor.py:840} INFO - DAG(s) 'put_data_to_db' retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:23:51.928+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:23:51.928+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-07-21T14:23:51.971+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:23:51.970+0000] {dag.py:3823} INFO - Setting next_dagrun for put_data_to_db to 2025-07-21 00:00:00+00:00, run_after=2025-07-22 00:00:00+00:00
[2025-07-21T14:23:52.013+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.177 seconds
[2025-07-21T14:23:52.972+0000] {processor.py:161} INFO - Started process (PID=244) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:23:52.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:23:52.975+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:23:52.975+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:23:53.018+0000] {processor.py:840} INFO - DAG(s) 'put_data_to_db' retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:23:53.051+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:23:53.051+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-07-21T14:23:53.083+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:23:53.083+0000] {dag.py:3823} INFO - Setting next_dagrun for put_data_to_db to 2025-07-21 00:00:00+00:00, run_after=2025-07-22 00:00:00+00:00
[2025-07-21T14:23:53.118+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.152 seconds
[2025-07-21T14:23:54.099+0000] {processor.py:161} INFO - Started process (PID=249) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:23:54.100+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:23:54.101+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:23:54.101+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:23:54.139+0000] {processor.py:840} INFO - DAG(s) 'put_data_to_db' retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:23:54.181+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:23:54.181+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-07-21T14:23:54.212+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:23:54.212+0000] {dag.py:3823} INFO - Setting next_dagrun for put_data_to_db to 2025-07-21 00:00:00+00:00, run_after=2025-07-22 00:00:00+00:00
[2025-07-21T14:23:54.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.155 seconds
[2025-07-21T14:24:24.489+0000] {processor.py:161} INFO - Started process (PID=254) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:24:24.490+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:24:24.491+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:24:24.490+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:24:24.506+0000] {processor.py:840} INFO - DAG(s) 'put_data_to_db' retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:24:24.529+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:24:24.529+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-07-21T14:24:24.548+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:24:24.548+0000] {dag.py:3823} INFO - Setting next_dagrun for put_data_to_db to 2025-07-21 00:00:00+00:00, run_after=2025-07-22 00:00:00+00:00
[2025-07-21T14:24:24.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.084 seconds
[2025-07-21T14:24:54.714+0000] {processor.py:161} INFO - Started process (PID=259) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:24:54.715+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:24:54.716+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:24:54.716+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:24:54.734+0000] {processor.py:840} INFO - DAG(s) 'put_data_to_db' retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:24:54.766+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:24:54.766+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-07-21T14:24:54.790+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:24:54.789+0000] {dag.py:3823} INFO - Setting next_dagrun for put_data_to_db to 2025-07-21 00:00:00+00:00, run_after=2025-07-22 00:00:00+00:00
[2025-07-21T14:24:54.816+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.105 seconds
[2025-07-21T14:25:25.172+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:25:25.174+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:25:25.178+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:25:25.177+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:25:25.228+0000] {processor.py:840} INFO - DAG(s) 'put_data_to_db' retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:25:25.286+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:25:25.286+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-07-21T14:25:25.332+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:25:25.332+0000] {dag.py:3823} INFO - Setting next_dagrun for put_data_to_db to 2025-07-21 00:00:00+00:00, run_after=2025-07-22 00:00:00+00:00
[2025-07-21T14:25:25.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.196 seconds
[2025-07-21T14:25:55.516+0000] {processor.py:161} INFO - Started process (PID=269) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:25:55.519+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:25:55.521+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:25:55.520+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:25:55.587+0000] {processor.py:840} INFO - DAG(s) 'put_data_to_db' retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:25:55.627+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:25:55.627+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-07-21T14:25:55.654+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:25:55.653+0000] {dag.py:3823} INFO - Setting next_dagrun for put_data_to_db to 2025-07-21 00:00:00+00:00, run_after=2025-07-22 00:00:00+00:00
[2025-07-21T14:25:55.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.177 seconds
[2025-07-21T14:26:25.978+0000] {processor.py:161} INFO - Started process (PID=274) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:26:25.980+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:26:25.983+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:26:25.982+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:26:26.031+0000] {processor.py:840} INFO - DAG(s) 'put_data_to_db' retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:26:26.069+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:26:26.069+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-07-21T14:26:26.111+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:26:26.111+0000] {dag.py:3823} INFO - Setting next_dagrun for put_data_to_db to 2025-07-21 00:00:00+00:00, run_after=2025-07-22 00:00:00+00:00
[2025-07-21T14:26:26.145+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.172 seconds
[2025-07-21T14:26:56.279+0000] {processor.py:161} INFO - Started process (PID=279) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:26:56.282+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:26:56.284+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:26:56.283+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:26:56.332+0000] {processor.py:840} INFO - DAG(s) 'put_data_to_db' retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:26:56.363+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:26:56.363+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-07-21T14:26:56.393+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:26:56.392+0000] {dag.py:3823} INFO - Setting next_dagrun for put_data_to_db to 2025-07-21 00:00:00+00:00, run_after=2025-07-22 00:00:00+00:00
[2025-07-21T14:26:56.421+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.148 seconds
[2025-07-21T14:27:16.676+0000] {processor.py:161} INFO - Started process (PID=284) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:27:16.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:27:16.679+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:27:16.679+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:27:16.704+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:27:16.703+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/put_data_to_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/put_data_to_db.py", line 44
    context['ti'].xcom_push(key='user_data', value=data)
    ^
IndentationError: unexpected indent
[2025-07-21T14:27:16.705+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:27:16.733+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.060 seconds
[2025-07-21T14:27:18.770+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:27:18.772+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:27:18.775+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:27:18.774+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:27:18.828+0000] {processor.py:840} INFO - DAG(s) 'put_data_to_db' retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:27:18.863+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:27:18.862+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-07-21T14:27:18.893+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:27:18.892+0000] {dag.py:3823} INFO - Setting next_dagrun for put_data_to_db to 2025-07-21 00:00:00+00:00, run_after=2025-07-22 00:00:00+00:00
[2025-07-21T14:27:18.925+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.158 seconds
[2025-07-21T14:27:23.105+0000] {processor.py:161} INFO - Started process (PID=294) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:27:23.108+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:27:23.110+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:27:23.109+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:27:23.157+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:27:23.156+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/put_data_to_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/put_data_to_db.py", line 45
    else:
    ^
SyntaxError: invalid syntax
[2025-07-21T14:27:23.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:27:23.214+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.114 seconds
[2025-07-21T14:27:28.152+0000] {processor.py:161} INFO - Started process (PID=299) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:27:28.154+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:27:28.156+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:27:28.156+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:27:28.225+0000] {processor.py:840} INFO - DAG(s) 'put_data_to_db' retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:27:28.304+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:27:28.303+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-07-21T14:27:28.362+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:27:28.361+0000] {dag.py:3823} INFO - Setting next_dagrun for put_data_to_db to 2025-07-21 00:00:00+00:00, run_after=2025-07-22 00:00:00+00:00
[2025-07-21T14:27:28.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.255 seconds
[2025-07-21T14:27:58.678+0000] {processor.py:161} INFO - Started process (PID=304) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:27:58.680+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:27:58.682+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:27:58.681+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:27:58.758+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:27:58.750+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/put_data_to_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/put_data_to_db.py", line 63, in <module>
    python_callable=connect_to_db,
NameError: name 'connect_to_db' is not defined
[2025-07-21T14:27:58.760+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:27:58.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.115 seconds
[2025-07-21T14:28:03.807+0000] {processor.py:161} INFO - Started process (PID=309) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:28:03.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:28:03.813+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:28:03.813+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:28:03.877+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:28:03.870+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/put_data_to_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/put_data_to_db.py", line 63, in <module>
    python_callable=connect_to_db,
NameError: name 'connect_to_db' is not defined
[2025-07-21T14:28:03.880+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:28:03.914+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.118 seconds
[2025-07-21T14:28:05.946+0000] {processor.py:161} INFO - Started process (PID=314) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:28:05.948+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:28:05.950+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:28:05.949+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:28:06.007+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:28:06.001+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/put_data_to_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/put_data_to_db.py", line 63, in <module>
    python_callable=connect_to_db,
NameError: name 'connect_to_db' is not defined
[2025-07-21T14:28:06.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:28:06.034+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.094 seconds
[2025-07-21T14:28:16.191+0000] {processor.py:161} INFO - Started process (PID=319) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:28:16.193+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:28:16.195+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:28:16.195+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:28:16.280+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:28:16.268+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/put_data_to_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/put_data_to_db.py", line 63, in <module>
    python_callable=connect_to_db,
NameError: name 'connect_to_db' is not defined
[2025-07-21T14:28:16.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:28:16.324+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.139 seconds
[2025-07-21T14:28:18.220+0000] {processor.py:161} INFO - Started process (PID=324) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:28:18.222+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:28:18.223+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:28:18.223+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:28:18.276+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:28:18.268+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/put_data_to_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/put_data_to_db.py", line 63, in <module>
    python_callable=connect_to_db,
NameError: name 'connect_to_db' is not defined
[2025-07-21T14:28:18.279+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:28:18.308+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.093 seconds
[2025-07-21T14:28:48.484+0000] {processor.py:161} INFO - Started process (PID=329) to work on /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:28:48.486+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/put_data_to_db.py for tasks to queue
[2025-07-21T14:28:48.487+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:28:48.487+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:28:48.506+0000] {logging_mixin.py:188} INFO - [2025-07-21T14:28:48.502+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/put_data_to_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/put_data_to_db.py", line 63, in <module>
    python_callable=connect_to_db,
NameError: name 'connect_to_db' is not defined
[2025-07-21T14:28:48.507+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/put_data_to_db.py
[2025-07-21T14:28:48.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/put_data_to_db.py took 0.048 seconds
